# Generated by Django 2.2.7 on 2019-11-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ffdonations', '0023_donationtiltifymodel_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationmodel',
            name='univ',
            field=models.IntegerField(default=None, null=True, verbose_name='Universal Donation PK'),
        ),
        migrations.AddField(
            model_name='donationtiltifymodel',
            name='univ',
            field=models.IntegerField(default=None, null=True, verbose_name='Universal Donation PK'),
        ),
    ]
