# Generated by Django 2.2.7 on 2019-11-25 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('ffsfdc', '0004_donation'),
        ('ffdonations', '0023_donationtiltifymodel_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationmodel',
            name='univ',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='ffsfdc.Donation', verbose_name='Universal Donation'),
        ),
    ]
