# Generated by Django 2.2.7 on 2019-11-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ffsfdc', '0003_auto_20190811_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id_c',
                 models.CharField(blank=True, db_column='sync_id__c', max_length=255, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('sfid', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('donation_record_c',
                 models.CharField(blank=True, db_column='donation_record__c', max_length=255, null=True)),
                ('donated_at_c', models.DateTimeField(blank=True, db_column='donated_at__c', null=True)),
                ('charity_c', models.CharField(blank=True, db_column='charity__c', max_length=255, null=True)),
                ('contact_c', models.CharField(blank=True, db_column='contact__c', max_length=18, null=True)),
                ('lastmodifieddate', models.DateTimeField(blank=True, null=True)),
                ('ownerid', models.CharField(blank=True, max_length=18, null=True)),
                ('mayedit', models.BooleanField(blank=True, null=True)),
                ('isdeleted', models.BooleanField(blank=True, null=True)),
                ('systemmodstamp', models.DateTimeField(blank=True, null=True)),
                ('lastmodifiedbyid', models.CharField(blank=True, max_length=18, null=True)),
                ('lastactivitydate', models.DateField(blank=True, null=True)),
                ('islocked', models.BooleanField(blank=True, null=True)),
                ('createddate', models.DateTimeField(blank=True, null=True)),
                ('createdbyid', models.CharField(blank=True, max_length=18, null=True)),
                ('pledged_at_c', models.DateTimeField(blank=True, db_column='pledged_at__c', null=True)),
                ('donation_amount_c', models.FloatField(blank=True, db_column='donation_amount__c', null=True)),
                ('amount_pledged_c', models.FloatField(blank=True, db_column='amount_pledged__c', null=True)),
                ('currencyisocode', models.CharField(blank=True, max_length=3, null=True)),
                ('field_hc_lastop', models.CharField(blank=True, db_column='_hc_lastop', max_length=32, null=True)),
                ('field_hc_err', models.TextField(blank=True, db_column='_hc_err', null=True)),
            ],
            options={
                'db_table': 'donation__c',
                'managed': False,
            },
        ),
    ]
